# Use a build matrix to run one set of jobs that test the conda environments
# and another to test the URLs in the Markdown files
# See https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
matrix:
  include:
  # Configuration adapted from https://github.com/gitter-lab/t-cell-classification
  - language: minimal
    os:
      - linux
      - osx
    before_install:
      - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          echo Testing in Linux
        fi
      - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          echo Testing in osx
        fi

  # Configuration adapted from https://github.com/dkhamsing/awesome_bot
  - language: ruby
    rvm: 2.4.1
    before_script: gem install awesome_bot
    script: awesome_bot guide/*.md --allow-redirect --allow-dupe

notifications:
  email: false
