# Use a build matrix to run one set of jobs that test the conda environments
# and another to test the URLs in the Markdown files
# See https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
matrix:
  include:
  # Configuration adapted from https://github.com/gitter-lab/t-cell-classification
  - language: minimal
    os: linux
    before_install:
      - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh -O miniconda.sh
      - bash miniconda.sh -b -p $HOME/anaconda
      - export PATH="$HOME/anaconda/bin:$PATH"
    script:
      - cd scripts
      - ./install_launch_linux.sh

  - language: minimal
    os: osx
    before_install:
      - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.12-MacOSX-x86_64.sh -O miniconda.sh
      - bash miniconda.sh -b -p $HOME/anaconda
      - export PATH="$HOME/anaconda/bin:$PATH"
    script:
      - cd scripts
      - ./install_launch_mac.command

  # Configuration adapted from https://github.com/dkhamsing/awesome_bot
  - language: ruby
    rvm: 2.4.1
    before_script: gem install awesome_bot
    script: awesome_bot guide/*.md --allow-redirect --allow-dupe

notifications:
  email: false
